### ISSUE TITLE
build qtdrv on windows7 x64 failed 

### ISSUE THREAD

**Issue by vanloswang** [visualfc/go-ui#16]
when execute the follow cmd, it failed to build go-ui on Windows 7 64 bit system.
$ cd go-ui/ui
$ go install
The error message is as below:
In file included from $WORK\github.com\vanloswang\go-ui\ui\_obj\_cgo_export.c:2:
0:
.\cdrv.go:64:14: error: conflicting types for 'drv_result'
  Data uintptr
              ^
.\cdrv.go:25:13: note: previous declaration of 'drv_result' was here
  extern int drv_result(void*,int);
             ^
.\cdrv.go:68:14: error: conflicting types for 'drv_callback'

              ^
.\cdrv.go:13:13: note: previous declaration of 'drv_callback' was here
  extern int drv_callback(void*,void*,void*,void*,void*);
             ^

F:\GoLang\GoDev\src\github.com\vanloswang\go-ui\ui>go install
# github.com/vanloswang/go-ui/ui
In file included from $WORK\github.com\vanloswang\go-ui\ui\_obj\_cgo_export.c:2:
0:
.\cdrv.go:64:14: error: conflicting types for 'drv_result'
  Data uintptr
              ^
.\cdrv.go:25:13: note: previous declaration of 'drv_result' was here
  extern int drv_result(void*,int);
             ^
.\cdrv.go:68:14: error: conflicting types for 'drv_callback'

              ^
.\cdrv.go:13:13: note: previous declaration of 'drv_callback' was here
  extern int drv_callback(void*,void*,void*,void*,void*);
             ^
anyone have some suggestions?

**Comment by vanloswang** [comment]
fixed

**Comment by syzer** [comment]
great work 👍
